export const ROUTES = Object.freeze({
  splash: "/",
  welcome: "/welcome",
  onboarding: "/onboarding",
  signIn: "/auth/sign-in",
  signUp: "/auth/sign-up",
  phone: "/auth/phone",
  otp: "/auth/otp",
  verifyEmail: "/auth/verify-email",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  passwordUpdated: "/auth/password-updated",
  sessionExpired: "/auth/session-expired",
  logout: "/auth/logout",
  unauthorized: "/unauthorized",
  home: "/home",
  rides: "/rides",
  wallet: "/wallet",
  profile: "/profile",
  book: "/book",
  searching: "/searching",
  driver: "/driver",
  driverApply: "/driver/apply",
  adminFinance: "/admin/finance",
});

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
